apiVersion: v1
metadata:
  name: keycloak
kind: Namespace
spec: {}
---
apiVersion: v1
data:
  identities.yaml: Y3JlZGVudGlhbHM6CiAgLSB1c2VybmFtZTogYWRtaW4KICAgIHBhc3N3b3JkOiBhZG1pbiAKICAgIHJvbGVzOgogICAgICAtIGFkbWluCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: connect-secret
  namespace: keycloak
---
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan 
  namespace: keycloak
  annotations:
    infinispan.org/monitoring: 'true' 
spec:
  replicas: 3
  version: 14.0.17
  security:
    endpointSecretName: connect-secret 
  service:
    type: DataGrid
    sites:
      local:
        name: infinispan-remote
        expose:
          type: LoadBalancer 
        maxRelayNodes: 128
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: sessions
  namespace: keycloak
spec:
  clusterName: infinispan
  name: sessions
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      stateTransfer:
        chunkSize: 16
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: authentication-sessions
  namespace: keycloak
spec:
  clusterName: infinispan
  name: authenticationSessions
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      stateTransfer:
        chunkSize: 16
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: offline-sessions
  namespace: keycloak
spec:
  clusterName: infinispan
  name: offlineSessions
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      stateTransfer:
        chunkSize: 16
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: client-sessions
  namespace: keycloak
spec:
  clusterName: infinispan
  name: clientSessions
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      stateTransfer:
        chunkSize: 16
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: offline-client-sessions
  namespace: keycloak
spec:
  clusterName: infinispan
  name: offlineClientSessions
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      stateTransfer:
        chunkSize: 16
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: login-failures
  namespace: keycloak
spec:
  clusterName: infinispan
  name: loginFailures
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      stateTransfer:
        chunkSize: 16
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: action-tokens
  namespace: keycloak
spec:
  clusterName: infinispan
  name: actionTokens
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      stateTransfer:
        chunkSize: 16
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: work
  namespace: keycloak
spec:
  clusterName: infinispan
  name: work
  template: |-
    replicatedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      stateTransfer:
        chunkSize: 16
